
services:

  # 👑 Master Node (NameNode + ResourceManager)
  master-node:
    image: master-node:341
    container_name: master-node
    hostname: master-node
    networks:
      - hadoop-network
    ports:
      - "9870:9870"   # NameNode UI
      - "8088:8088"   # ResourceManager UI
      - "9868:9868"
    volumes:
      - master-data:/opt/hadoop/data
    cap_add:
      - SYS_NICE
    depends_on:
      - worker-node-1
      - worker-node-2
    restart: unless-stopped

  # 🚀 Worker 1 (DataNode + NodeManager)
  worker-node-1:
    image: worker-node:341
    container_name: worker-node-1
    hostname: worker-node-1
    networks:
      - hadoop-network
    ports:
      - "9864:9864"   # DataNode UI
      - "8042:8042"   # NodeManager UI
      
    volumes:
      - worker-data-1:/opt/hadoop/data
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  # 🚀 Worker 2 (DataNode + NodeManager)
  worker-node-2:
    image: worker-node:341
    container_name: worker-node-2
    hostname: worker-node-2
    networks:
      - hadoop-network
    ports:
      - "9865:9864"   # DataNode UI
      - "8043:8042"   # NodeManager UI
    volumes:
      - worker-data-2:/opt/hadoop/data
    cap_add:
      - SYS_NICE
    restart: unless-stopped

# 🔗 Redes
networks:
  hadoop-network:
    name: hadoop-network
    driver: bridge

# 💾 Volúmenes persistentes
volumes:
  master-data:
  worker-data-1:
  worker-data-2:

# Still need to add the following lines to the master-node Dockerfile:
# - conf_volume(path):/opt/hadoop/etc/hadoop Map config files to a volume
# /opt/hadoop/logs Esta carpeta no esta mapeada a un volumen, por lo que los logs se perderán al reiniciar el contenedor.

# secondary namenode
# Checkpoint Image URI
# file:///tmp/hadoop-hadoop/dfs/namesecondary
# Checkpoint Editlog URI
# file:///tmp/hadoop-hadoop/dfs/namesecondary
# Investigate the secondary namenode URI