FROM ubuntu:24.04

RUN pwd >> pwd_output_2.txt
# docker run --hostname=4658dab1aa8c --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --network=bridge --restart=no --label='org.opencontainers.image.ref.name=ubuntu' --label='org.opencontainers.image.version=24.04' --runtime=runc -d hadoop:master