version: "3.9"

services:
  hadoop:
    image: pseudo:341                      # Imagen local creada desde el Dockerfile
    container_name: pseudo-distributed      # Nombre del contenedor
    hostname: pseudo-distributed   
    ports:
      - "9870:9870"   # NameNode UI (http://localhost:9870)
      - "8088:8088"   # ResourceManager UI (http://localhost:8088)
      - "9864:9864"   # DataNode UI (http://localhost:9864)
      - "8042:8042"   # NodeManager UI (http://localhost:8042)
    stdin_open: true   # Mantiene la consola abierta (equivalente a -it)
    tty: true          # Permite terminal interactiva
